
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MLService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MLService {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMoy", targetNamespace = "http://service/", className = "service.GetMoy")
    @ResponseWrapper(localName = "getMoyResponse", targetNamespace = "http://service/", className = "service.GetMoyResponse")
    @Action(input = "http://service/MLService/getMoyRequest", output = "http://service/MLService/getMoyResponse")
    public double getMoy(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Double> arg0);

    /**
     * 
     * @return
     *     returns java.util.List<service.CompteDataScience>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://service/", className = "service.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://service/", className = "service.GetComptesResponse")
    @Action(input = "http://service/MLService/getComptesRequest", output = "http://service/MLService/getComptesResponse")
    public List<CompteDataScience> getComptes();

}
